// <auto-generated />
namespace Assignment_8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class promotion_vmupdate3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(promotion_vmupdate3));
        
        string IMigrationMetadata.Id
        {
            get { return "201702111808594_promotion_vm-update3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
